---
#
# Ansible managed
#
repository:
  description: Installs and configures watchtower container based on official watchtower docker container
  homepage: https://mullholland.net
  topics: cloud, development, webserver, watchtower, proxy, ansible, molecule, tox, playbook
