---
- name: watchtower | set application facts
  ansible.builtin.set_fact:
    app_name: "watchtower"
    app_image: "{{ watchtower_docker_version }}"
    app_network: "{{ watchtower_docker_network_name }}"
    app_base_path: "{{ watchtower_docker_base_path }}"
    app_user: "{{ watchtower_docker_user }}"
    app_uid: "{{ watchtower_docker_uid }}"
    app_group: "{{ watchtower_docker_group }}"
    app_gid: "{{ watchtower_docker_gid }}"
    app_timezone: "{{ watchtower_docker_timezone }}"
    app_environment_variables: "{{ watchtower_docker_environment_variables }}"
    app_volumes: "{{ watchtower_docker_volumes }}"
    app_labels: "{{ watchtower_docker_labels }}"
    app_ports: "{{ watchtower_docker_ports }}"

- name: watchtower | get docker executable path
  ansible.builtin.command:
    cmd: "which docker"
  changed_when: false
  register: watchtower_docker_executable_path

- name: "watchtower | create docker-compose.yml"
  ansible.builtin.template:
    src: "docker-compose.yml.j2"
    dest: "{{ app_base_path }}/{{ app_name }}/docker-compose.yml"
    mode: "0640"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
  notify: watchtower_restart

- name: "watchtower | Create systemd service"
  ansible.builtin.template:
    src: "systemd.service.j2"
    dest: "/etc/systemd/system/{{ app_name }}.service"
    mode: "0770"
    owner: "root"
    group: "root"
  notify:
    - watchtower_systemd_reload
    - watchtower_restart
